M48
; DRILL file {KiCad (6.0.7)} date Tue Nov  8 16:58:02 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-11-08T16:58:02+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X1.2982Y-1.4921
X1.2982Y-3.311
T2
X1.1811Y-1.1811
X1.1811Y-4.3307
X4.3307Y-1.1811
X4.3307Y-4.3307
T0
M30
